version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.4
        environment:
          DATABASE_URL: postgresql://root@localhost/circle_test?sslmode=disable
      - image: circleci/postgres:9.6.2
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: {{ project_name }}
      - image: circleci/redis
    steps:
      - checkout
      - restore_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
      - run:
          command: pipenv install --dev
      - save_cache:
          key: deps-{{ checksum "Pipfile.lock" }}
          paths:
            - "env"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          command: pipenv run manage.py test
